// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notification.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20251213003350_AddNotificationFields")]
    partial class AddNotificationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notification.Domain.Entities.CargaArchivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("email_error");

                    b.Property<string>("EmailStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email_status");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFinProceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_proceso");

                    b.Property<DateTime?>("FechaInicioProceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_proceso");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("FileId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_id");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mensaje_error");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre_archivo");

                    b.Property<DateTime?>("NotificadoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notificado_at");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo");

                    b.Property<int>("RegistrosExitosos")
                        .HasColumnType("integer")
                        .HasColumnName("registros_exitosos");

                    b.Property<int>("RegistrosFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("registros_fallidos");

                    b.Property<int>("RegistrosProcesados")
                        .HasColumnType("integer")
                        .HasColumnName("registros_procesados");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("integer")
                        .HasColumnName("total_registros");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("cargas_archivos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
