// <auto-generated />
using System;
using FileControl.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileControl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FileControlDbContext))]
    partial class FileControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileControl.Domain.Entities.CargaArchivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFinProceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_proceso");

                    b.Property<DateTime?>("FechaInicioProceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_proceso");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("FileId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_id");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mensaje_error");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo");

                    b.Property<int>("RegistrosExitosos")
                        .HasColumnType("integer")
                        .HasColumnName("registros_exitosos");

                    b.Property<int>("RegistrosFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("registros_fallidos");

                    b.Property<int>("RegistrosProcesados")
                        .HasColumnType("integer")
                        .HasColumnName("registros_procesados");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("integer")
                        .HasColumnName("total_registros");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_cargas_archivos_estado");

                    b.HasIndex("Periodo")
                        .HasDatabaseName("ix_cargas_archivos_periodo");

                    b.HasIndex("Usuario")
                        .HasDatabaseName("ix_cargas_archivos_usuario");

                    b.ToTable("cargas_archivos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
